In [84]:
import numpy as np
import pandas as pd
Data={'Names':['Ramesh','Suesh','Satish',np.nan],
      'Age':[np.nan,22,25,27],
      'City':['Pune','Pune',np.nan,'Hyd']}
df=pd.DataFrame(Data)
df

,Names,Age,City
0,Ramesh,NaN,Pune
1,Suesh,22.0,Pune
2,Satish,25.0,None
3,None,27.0,Hyd


In [86]:
df.to_csv('data_missing.csv',index=False)

In [88]:
import numpy as np
import pandas as pd
Data={'Names':['Ramesh','Suesh','Satish',None],
      'Age':[None,22,25,27],
      'City':['Pune','Pune',None,'Hyd']}
df1=pd.DataFrame(Data)
df1

,Names,Age,City
0,Ramesh,NaN,Pune
1,Suesh,22.0,Pune
2,Satish,25.0,None
3,None,27.0,Hyd


In [90]:
df1.to_csv('data_missing.csv',index=False)

In [92]:
df1.dtypes

Names     object
Age      float64
City      object
dtype: object

In [6]:
df.dtypes

Names     object
Age      float64
City      object
dtype: object

## **isnull**

In [8]:
df.isnull()

,Names,Age,City
0,False,True,False
1,False,False,False
2,False,False,True
3,True,False,False


In [9]:
df.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

In [10]:
df1.isnull()

,Names,Age,City
0,False,True,False
1,False,False,False
2,False,False,True
3,True,False,False


In [11]:
df1.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

In [12]:
df.fillna(30)#not recomandent

,Names,Age,City
0,Ramesh,30.0,Pune
1,Suesh,22.0,Pune
2,Satish,25.0,30
3,30,27.0,Hyd


## **what is the difference between np.nan and None**

In [14]:
np.nan+5

nan

In [15]:
None+5

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [32]:
arr1=np.array([1,2,np.nan,3])
arr2=np.array([1,2,None,3])

In [34]:
arr1

array([ 1.,  2., nan,  3.])

In [36]:
arr2

array([1, 2, None, 3], dtype=object)

In [38]:
np.nansum(arr1)

6.0

In [40]:
np.sum(arr1)

nan

In [42]:
np.nansum(arr2)

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [ ]:
np.sum(arr2)

- np,nan reperesented **float type**
- None represented **object type**
- if data operations related to Maths then nan format is better

## **Fill the value based on column**

In [ ]:
#df.filna

- pad
- bfill
- ffill
- backfill

In [55]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='pad')

,Names,Age,City
0,Ramesh,NaN,Pune
1,Suesh,22.0,Pune
2,Satish,25.0,Pune
3,Satish,27.0,Hyd


In [57]:
df.fillna(method='bfill')

,Names,Age,City
0,Ramesh,22.0,Pune
1,Suesh,22.0,Pune
2,Satish,25.0,Hyd
3,NaN,27.0,Hyd


In [58]:
df.fillna(method='ffill')

,Names,Age,City
0,Ramesh,NaN,Pune
1,Suesh,22.0,Pune
2,Satish,25.0,Pune
3,Satish,27.0,Hyd


In [60]:
df.fillna(method='backfill')

,Names,Age,City
0,Ramesh,22.0,Pune
1,Suesh,22.0,Pune
2,Satish,25.0,Hyd
3,NaN,27.0,Hyd


In [61]:
df.fillna(method='pad',axis=1)

,Names,Age,City
0,Ramesh,Ramesh,Pune
1,Suesh,22.0,Pune
2,Satish,25.0,25.0
3,NaN,27.0,Hyd


In [63]:
df.fillna(method='bfill',axis=1)

,Names,Age,City
0,Ramesh,Pune,Pune
1,Suesh,22.0,Pune
2,Satish,25.0,NaN
3,27.0,27.0,Hyd


## **Mean-Median_Mode**

In [65]:
idea-1: filling with random value = df.fillname(<random valuea>)
idea-2: filling with rv bsed on column=df[<col>].fillname(<random valuea>)
idea-3: filling with some pattern using a method: df.fillna(<method>)
idea-4: filling with m-m-m based on column=df[<col>].fillname(<mean> or <median> or <mode>)
idea-5: filling with avg value only selected nighbours
idea-5: filling with a based

NameError: name 'data1' is not defined

In [98]:
data1=df

In [100]:
age_mean=data1['Age'].mean()
print('age_mean:',age_mean)
data1['Age'].fillna(age_mean)

age_mean: 24.666666666666668


0    24.666667
1    22.000000
2    25.000000
3    27.000000
Name: Age, dtype: float64

In [102]:
city_mode.values[0]

NameError: name 'city_mode' is not defined

- in future sometimes if we direct impute mode value we will get error
- mode is comming as series
- mean is coming as fixed value
- so first convert series to fixed 

## **impute class**

- under the sklearn we have impute class is there

<!-- from sklearn import impute -->

In [107]:
from sklearn import impute

## **KNM Immputer**

- k- Nearest Neighbour
- where k= hyper parameter which means the user can change
- idea: instead of taking all the samples average
    - First fix the neighbour number i.e k
    - Then find the neighbours using distance metric
    - then take the average of those samples to fill the missing value

In [76]:
import numpy as np
from sklearn.impute import KNNImputer
X=[[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
imputer=KNMImputer(n_neighbors=2,weights='distance')
imputer.fit_transform(X)

NameError: name 'KNMImputer' is not defined

In [115]:
import numpy as np
from sklearn.impute import KNNImputer

# Sample data with missing values
X = [[1, 2, np.nan], [3, np.nan, 3], [np.nan, 60, 5], [8, 8, 7]]

# Create the KNN imputer
imputer = KNNImputer(n_neighbors=2, weights='distance')

# Fit the imputer and transform the data
X_imputed = imputer.fit_transform(X)

print(X_imputed)


[[ 1.          2.          3.93905505]
 [ 3.         31.          3.        ]
 [ 3.25775362 60.          5.        ]
 [ 8.          8.          7.        ]]


In [3]:
import pandas as pd
import numpy as np

In [7]:
dict1={'Name':['Ramesh','Suresh','Satish',np.nan],
       'Age':[30,33,np.nan,36],
       'City':[np.nan,'Hyd','bel','blr']
      }

In [9]:
df=pd.DataFrame(dict1)
df

,Name,Age,City
0,Ramesh,30.0,NaN
1,Suresh,33.0,Hyd
2,Satish,NaN,bel
3,NaN,36.0,blr


In [13]:
df.to_csv('data_missings.csv',index=False)

In [15]:
df.isnull().sum()

Name    1
Age     1
City    1
dtype: int64

## **dropna**

- drop  the null values data based on rows and columns

In [19]:
#i want to extract the data with out null values
df.dropna()

,Name,Age,City
1,Suresh,33.0,Hyd


In [23]:
df.dropna(axis=1)

""
0
1
2
3


In [25]:
dict1={'Name':['Ramesh','Suresh','Satish',np.nan],
       'Age':[30,33,np.nan,36],
       'City':[np.nan,'Hyd','bel','blr'],
       'Compony':['Google','Microsoft','Apple','Meta']
      }
df1=pd.DataFrame(dict1)
df1

,Name,Age,City,Compony
0,Ramesh,30.0,NaN,Google
1,Suresh,33.0,Hyd,Microsoft
2,Satish,NaN,bel,Apple
3,NaN,36.0,blr,Meta


In [27]:
df1.fillna(30)

,Name,Age,City,Compony
0,Ramesh,30.0,30,Google
1,Suresh,33.0,Hyd,Microsoft
2,Satish,30.0,bel,Apple
3,30,36.0,blr,Meta


In [29]:
df1['Name'].fillna('Manish')

0    Ramesh
1    Suresh
2    Satish
3    Manish
Name: Name, dtype: object

**Draw back:is not good

- TO Avoid we have some methods
  - backfill
  - bfill
  - ffill
  - pad

In [44]:
import warnings
warnings.filterwarnings('ignore')
df1.fillna(method='pad')

,Name,Age,City,Compony
0,Ramesh,30.0,NaN,Google
1,Suresh,33.0,Hyd,Microsoft
2,Satish,33.0,bel,Apple
3,Satish,36.0,blr,Meta


In [46]:
import warnings
warnings.filterwarnings('ignore')
df1.fillna(method='pad',axis=1)

,Name,Age,City,Compony
0,Ramesh,30.0,30.0,Google
1,Suresh,33.0,Hyd,Microsoft
2,Satish,Satish,bel,Apple
3,NaN,36.0,blr,Meta


In [48]:
import warnings
warnings.filterwarnings('ignore')
df1.fillna(method='ffill')

,Name,Age,City,Compony
0,Ramesh,30.0,NaN,Google
1,Suresh,33.0,Hyd,Microsoft
2,Satish,33.0,bel,Apple
3,Satish,36.0,blr,Meta


In [50]:
import warnings
warnings.filterwarnings('ignore')
df1.fillna(method='bfill')

,Name,Age,City,Compony
0,Ramesh,30.0,Hyd,Google
1,Suresh,33.0,Hyd,Microsoft
2,Satish,36.0,bel,Apple
3,NaN,36.0,blr,Meta


## **Mean-Median-Mode**

- numerical:mean or median
- categorical= mode
- outlier= media

In [62]:
age_mean=df1['Age'].mean()
print('age_mean:',age_mean)
df1['Age'].fillna(age_mean)

age_mean: 33.0


0    30.0
1    33.0
2    33.0
3    36.0
Name: Age, dtype: float64

In [66]:
city_model=df1['City'].mode()
city_model.values[0]

'Hyd'

## **impute class**

- under the we have impute class is there

In [70]:
from sklearn import impute

In [72]:
dir(impute)

['KNNImputer',
 'MissingIndicator',
 'SimpleImputer',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_base',
 '_knn',
 'typing']

In [ ]:
- distance method in ml
- euclidian
- jaccord or jacobian
- manhattan
- Cosine===RAG   where to use and how to use i want formula i want aplication where will use 
- find the relation betn 

In [ ]:
import numpy as np
from sklearn.impute import KNNImputerimport numpy as np
from sklearn.impute import KNNImputer
X=[[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
imputer=KNMImputer(n_neighbors=2,weights='distance')
imputer.fit_transform(X)